[package]
name = "kay_codegen"
version = "0.1.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]

[dependencies]
syn = "=0.11.11"
quote = "0.3.15"
ordermap = "0.3.2"
glob = "0.2.11"

[dev-dependencies]
pretty_assertions = "0.4.1"

[features]
default = ["syn/full"]
