language: node_js
node_js:
  - "latest"
sudo: required
git:
  depth: 9999999

matrix:
  include:
    - os: linux
      dist: trusty

    - os: osx
      osx_image: xcode9.4

    - os: windows

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r target
  - chmod -R a+r cb_browser_ui/target
  - chmod -R a+r $HOME/.rustup
  - chmod -R a+r $HOME/.cargo

cache:
  directories:
    - target
    - cb_browser_ui/target
    - $HOME/.rustup
    - $HOME/.cargo

addons:
  artifacts:
    s3_region: "eu-west-1"
    debug: true
    paths:
    - $(ls *-linux.tar.gz | tr "\n" ":")
    - $(ls *-osx.zip | tr "\n" ":")
    - $(ls *-windows-travis.exe | tr "\n" ":")
    target_paths:
    - /

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - npm run ensure-tooling

script:
  - npm run build-browser
  - npm run build-server-bundle
  - cd target/release/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv citybound citybound-$(cat ../../.version) && tar -pczf citybound-$(cat ../../.version)-linux.tar.gz citybound-$(cat ../../.version) && mv citybound-$(cat ../../.version)-linux.tar.gz ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv citybound citybound-$(cat ../../.version).command && zip citybound-$(cat ../../.version)-osx.zip citybound-$(cat ../../.version).command  && mv citybound-$(cat ../../.version)-osx.zip ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mv citybound.exe ../../citybound-$(cat ../../.version)-windows-travis.exe ; fi
  - cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint-check ; fi