dist: trusty
language: node_js
node_js:
  - "10.9.0"
sudo: required
osx_image: xcode9.4

env:
  global:
    # default job
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job

    # OSX
    #- env: TARGET=x86_64-apple-darwin DISABLE_TESTS=1
    #  os: osx

addons:
  artifacts:
    s3_region: "eu-west-1"
    debug: true
    paths:
    - ./target/release/citybound-linux.tar.gz
    target_paths:
    - /test/

before_install: set -e

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
  - source $HOME/.cargo/env
  - npm run ensure-tooling

script:
  - git fetch --unshallow
  - npm run build
  - cd target/release/
  - tar -pczf citybound-linux.tar.gz citybound
  - cd ..
  #- npm run lint-check

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  except:
    - /design-doc.*/
