language: node_js
node_js:
  - "10.9.0"
sudo: required
git:
  depth: 9999999

matrix:
  include:
    # Linux
    - os: linux
      dist: trusty

    # OSX
    - os: osx
      osx_image: xcode9.4

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r target
  - chmod -R a+r game_browser/target
  - chmod -R a+r $HOME/.rustup
  - chmod -R a+r $HOME/.cargo

cache:
  directories:
    - target
    - game_browser/target
    - $HOME/.rustup
    - $HOME/.cargo

addons:
  artifacts:
    s3_region: "eu-west-1"
    debug: true
    paths:
    - $(ls *-linux.tar.gz | tr "\n" ":")
    - $(ls *-osx.zip | tr "\n" ":")
    target_paths:
    - /

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352767521
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - npm run ensure-tooling

script:
  - npm run build
  - ls
  - cd target/release/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -pczf citybound-$(cat ../../.version)-linux.tar.gz citybound && mv citybound-$(cat ../../.version)-linux.tar.gz ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip citybound-$(cat ../../.version)-osx.zip citybound  && mv citybound-$(cat ../../.version)-osx.zip ../.. ; fi
  - cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint-check ; fi

branches:
  except:
    - /design-doc.*/
