os: Visual Studio 2015

environment:
  nodejs_version: "10"

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain none --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - ps: Install-Product node $env:nodejs_version
  - npm run ensure-tooling

build_script:
  - cd game_browser
  - npm install --no-save
  - cd ..
  - npm run build
  - for /f %%x in ('type .version') do ren "target\\release\\citybound.exe" "citybound-%%x-windows.exe"
  - for /f %%x in ('type .version') do appveyor PushArtifact "target\\release\\citybound-%%x-windows.exe"

deploy:
  provider: S3
  access_key_id:
    secure: jg+s3osFzmQXcD8igyJe3uuCdDdECyeuhvG3XSaVEF0=
  secret_access_key:
    secure: w0s1TKSKrKsI24IImGeX2EMeLoLgEckwTB50oBRO2PeFU0nbJLCT8nS9c6SQGVw6
  bucket: citybound.livebuilds
  region: eu-west-1
  folder: /