[package]
name = "citybound"
version = "0.1.2"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]
license = "AGPL-3.0"

[workspace]
members = [
    "./lib/allocators",
    "./lib/chunked",
    "./lib/compact",
    "./lib/compact_macros",
    "./lib/descartes",
    "./lib/kay",
    "./lib/kay_macros",
    "./lib/kay_codegen",
    "./lib/monet",
    './lib/stagemaster'
]

[dependencies]
ordered-float = "0.2.3"
itertools = "0.5.5"
clippy = { version = "0.0.138", optional = true }
random = "0.12.2"
fnv = "1.0.3"
roaring = "0.4.0"
open = "1.1.1"
serde = "1.0"
serde_derive = "1.0"
imgui = "0.0.11"

[dependencies.compact]
path = "./lib/compact/"

[dependencies.compact_macros]
path = "./lib/compact_macros/"

[dependencies.kay]
path = "./lib/kay/"

[dependencies.kay_macros]
path = "./lib/kay_macros/"

[dependencies.descartes]
path = "./lib/descartes/"

[dependencies.monet]
path = "./lib/monet/"

[dependencies.stagemaster]
path = "./lib/stagemaster/"

[profile.dev]
opt-level = 1
codegen-units = 4

[profile.release]
debug = true
codegen-units = 4

[features]
default = ["enable-clippy"]

enable-clippy = [
	"clippy",
	"compact/enable-clippy",
	"kay/enable-clippy",
	"descartes/clippy",
	"monet/enable-clippy",
	"stagemaster/enable-clippy"
]

