[package]
name = "citybound"
version = "0.3.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]
license = "AGPL-3.0"

[[bin]]
name = "citybound"
path = "./game_server/main.rs"

[dependencies.citybound_common]
path = "./game_common"

[profile.dev]
opt-level = 1
codegen-units = 4

[profile.release]
debug = true
codegen-units = 4

