[package]
name = "citybound"
version = "0.1.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]

[dependencies]
ordered-float = "*"
itertools = "*"
clippy = "*"
random = "*"

[dependencies.kay]
path = "./lib/kay/"

[dependencies.kay_macros]
path = "./lib/kay_macros/"

[dependencies.descartes]
path = "./lib/descartes/"

[dependencies.monet]
path = "./lib/monet/"

[profile.release]
debug = true
codegen-units = 4