[package]
name = "kay"
version = "0.1.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]

[dependencies]
byteorder = "1"

[dependencies.compact]
path = "../compact/"

[dependencies.compact_macros]
path = "../compact_macros/"

[dependencies.chunky]
path = "../chunky/"

