[package]
name = "citybound"
version = "0.1.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]

[dependencies]
nalgebra = "*"

[dependencies.kay]
path = "../kay/"

[dependencies.monet]
path = "../monet/"

[dependencies.compass]
path = "../compass/"