name: Build Citybound

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
        echo 'export PATH=$HOME/.cargo/bin:$PATH' >> ~/.bashrc
        tail -n 10 ~/.bashrc
        source ~/.bashrc
        rustup --version
      if: contains(matrix.os, 'macOS')
    - name: Ensure tooling installed
      run: npm run ensure-tooling
    - name: Build browser client
      run: npm run build-browser
    - name: Build server and create bundle
      run: npm run build-server-bundle
